# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [7]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print('Axes/dimensions: ', A.ndim,)  
print('Shape: ', A.shape)  
print('Size: ', A.size) 
print('Datatype: ', A.dtype)

Axes/dimensions:  2
Shape:  (3, 5)
Size:  15
Datatype:  int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
print(f'B-C:\n {B - C}\n')            # Elementwise subtraction.
print(f'B*C:\n {B * C}\n')            # Elementwise multiplication.
print(f'Matrix(B*C):\n {B @ C}\n')    # Matrix multiplication 

B-C:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

B*C:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix(B*C):
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(f'Numpy e^x where x is exach value in (Matrix B):\n {np.exp(B)}\n')               
print(f'Min value in B:\n {np.min(B)}\n')               
print(f'Min each row:\n {np.min(B,axis=0)}\n')  

print(f'Min each column:\n {np.min(B,axis=1)}\n')    
print(f'Min indexvalue for B:\n {np.argmin(B)}\n')            
print(f'Min indexvalue each row:\n {np.argmin(B,axis=0)}\n') 

print(f'Sum of B:\n {np.sum(B)}\n')              
print(f'Mean each column:\n {np.mean(B,axis=1)}\n')               
print(f'Median each column:\n  {np.median(B,axis=1)}\n') 

Numpy e^x where x is exach value in (Matrix B):
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Min value in B:
 1

Min each row:
 [1 2 3]

Min each column:
 [1 4 7]

Min indexvalue for B:
 0

Min indexvalue each row:
 [0 0 0]

Sum of B:
 45

Mean each column:
 [2. 5. 8.]

Median each column:
  [2. 5. 8.]



### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
# Fewer indices than axes when slicing a numpy array,the slicing applies to 
# the first axis by default. For 2D array, the first axis represents rows.
# Therefore, A[1] retrieves the entire second row of the array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
for i in A.flatten():   # or ravel() instead of flatten()
    print(i)
    
# Or oldschool for loop
# for i in A:
#    for x in i:
#        print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [8]:
# Creates a 1d vector/array with 30 elements   
# Reshapes the 1D array 'a' into (b) a 3D array with 2 group,3 rows in each group
# and automatically calculates the number of columns needed to maintain the
# same number of total elements (which is 5 columns in this case).
a = np.arange(30) 
b = a.reshape((2, 3, -1))

print(a)      
print()
print(b)  


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
##### Here's what's happening in general #####

# We're reshaping (a) to have a shape of three dimensions - (2, 3, -1)yy

# 1) The first dimension has a size of 2.
# 2) The second dimension has a size of 3.
# 3) The third dimension's size is not specified (-1). This means numpy will 
#    automatically determine the size for this dimension such that the total number 
#    of elements in the reshaped array (b) remains the same as in (a).


# 3 axes means:
# 1st Axis (Depth): Represents the primary sub-arrays. In this case two main subarrays
# 2nd Axis (Rows): Distinguishes between the rows inside each primary sub-array.
# 3rd Axis (Columns): Identifies the columns within every individual row.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [9]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)
print()
print(m1.shape,'\n',m2.shape)

[[2 3]
 [4 5]]

(2, 2) 
 (2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [10]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [11]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [12]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print('A:\n',A)
print('B:\n',B)
print('C:\n',C)
print('D:\n',D)
print('E:\n',E)

A:
 [[ 2  1 -1]
 [ 1 -1  1]]
B:
 [[ 4 -2  1]
 [ 2 -4 -2]]
C:
 [[1 2]
 [2 1]]
D:
 [[3 4]
 [4 3]]
E:
 [[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [13]:
def add_mult_matrices(x, y, math_method):
    
    if not (isinstance(x, np.ndarray) and isinstance(y, np.ndarray)):
        raise ValueError("Both inputs must be of type numpy.ndarray.")
    
    if math_method not in ['add', 'multiply']:
        raise ValueError("Method should be 'add' or 'multiply'")
    
    if math_method == 'add':
        if x.shape != y.shape:
            raise ValueError("Both matrices must have the same dimensions for addition.")
        return x + y
 
    elif math_method == 'multiply':
        if x.shape[1] != y.shape[0]:
            raise ValueError("Columns in the first matrix must be equal to rows in the second matrix for multiplication.")
        return x @ y
    

In [14]:

# Chap2. Question 1: B-2A

print(add_mult_matrices(B,-2*A,'add'))       

[[ 0 -4  3]
 [ 0 -2 -4]]


In [22]:
# Chap2. Question 1: 3C -E

add_mult_matrices(3*C, -E, 'add')          # not defined  

ValueError: Both matrices must have the same dimensions for addition.

In [15]:
# Chap2. Question 1: A*C

print(add_mult_matrices(A,C,'multiply'))   # not defined   

ValueError: Columns in the first matrix must be equal to rows in the second matrix for multiplication.

In [16]:
# Chap2. Question 1: C*D

print(add_mult_matrices(C,D,'multiply'))    

[[11 10]
 [10 11]]


In [17]:
# Chap2. Question 1: C*B

print(add_mult_matrices(C,B,'multiply'))     

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**

In [19]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = add_mult_matrices(A,B,'multiply')
AC = add_mult_matrices(A,C,'multiply')
print(f'AB = AC is  {np.array_equal(AB, AC)}\n')
print(f'B = C is  {np.array_equal(B, C)}')


AB = AC is  True

B = C is  False


**Chap2. Question 3**

In [20]:
A = np.array([[1, 1, 1], [1, 2, 3],[1, 3, 4]])
D = np.array([[2, 0, 0], [0, 3, 0],[0, 0, 4]])

AD = add_mult_matrices(A,D,'multiply')
DA = add_mult_matrices(D,A,'multiply')
print(f'AD = DA is  {np.array_equal(AD, DA)}')



AD = DA is  False


**Quiz p.11, Question 2**

In [22]:
G = np.array([[1, -1], [-1,  1]])
F = np.array([[-1, 1], [1,  -1]])

GF = add_mult_matrices(G,F,'multiply')
print('Matrix GF:\n',GF)


Matrix GF:
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [23]:
K = np.array([[5, 6], [4, 5]])
L = np.array([[6, 4], [3, 3]])
I = np.array([[1, 0], [0, 1]]) # identity matrix

K_inv = np.linalg.inv(K)  # Inverse of K
L_inv = np.linalg.inv(L)  # Inverse of K

# Verification by multiply matrix with it's inverse = should be I/Identity matrix
K_ver = add_mult_matrices(K, K_inv,'multiply')  
L_ver = add_mult_matrices(L, L_inv,'multiply')

I_K = np.round(K_ver).astype(int) #round each element in matrix to nearest whole nr
I_L = np.round(K_ver).astype(int)

print(f'Inverse Matrix K:\n{K_inv}\n {np.array_equal(I, I_K)}\n')
print(f'Inverse Matrix K:\n{L_inv}\n {np.array_equal(I, I_L)}')


# I know there is faster way but didnt have time to understand the allclose method 

Inverse Matrix K:
[[ 5. -6.]
 [-4.  5.]]
 True

Inverse Matrix K:
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]
 True


**Quiz p.19, Question 3**

In [24]:
Q = np.array([[2, 2], [1, 2]])
Q_inv = np.linalg.inv(Q)  # Inverse of K
I = np.array([[1, 0], [0, 1]]) # identity matrix

# Verification by multiply matrix with it's inverse = should be I/Identity matrix
Q_ver = add_mult_matrices(Q, Q_inv,'multiply')  
I_Q = np.round(Q_ver).astype(int) #round each element in matrix to nearest whole nr


print(f'Inverse Matrix Q:\n{Q_inv}\n {np.array_equal(I, I_Q)}\n')


Inverse Matrix Q:
[[ 1.  -1. ]
 [-0.5  1. ]]
 True



**Chap10. Question 1 a)**

In [25]:
P = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
T = np.array([-7, 5, 2])
print('x1,x2,x3 ->',np.linalg.solve(P,T))


x1,x2,x3 -> [ 3.  4. -6.]


**Chap10. Question 1 b)**

In [26]:
I = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
L = np.array([1, -1, 1])

print('x1,x2,x3 ->',np.linalg.solve(I,L))

x1,x2,x3 -> [ 8.  2. -1.]


**Chap 12. Question 1**

In [27]:
V = np.array([[3, -7, -2], [-3, 5, 1],[6, -4, 0]])
V_inv = np.linalg.inv(V)
I = [[1, 0, 0], [0, 1, 0],[0, 0, 1]] # Identity matrix

# Verification by multiply matrix with it's inverse = should be I/Identity matrix
V_ver = add_mult_matrices(V, V_inv,'multiply')  
I_V = np.round(V_ver).astype(int) #round each element in matrix to nearest whole nr


print(f'Inverse Matrix Q:\n{V_inv}\n {np.array_equal(I, I_V)}\n')




Inverse Matrix Q:
[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]
 True



### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

In [ ]:
# In numpy:

# 1. Views, not Copies: Numpy prefers to create views (references to the same data)
#    when slicing arrays.

# 2. Memory & Speed: This is efficient as copying large arrays consumes 
#    more memoryand is slower.

# 3. Data Consistency: Changes in a view are reflected in the original array, 
#   ensuring data remains consistent.


# To avoid unintended changes we use the .copy() method to get an independent data
# subset.